@startuml
!theme cerulean
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

top to bottom direction

Person(user, "Пользователь", "Мобильное приложение")

System(smartHouseSystem, "система Умный Дом", "Сервис управления устройствами")
System(authService, "Система авторизации", "auth-service-1")

System_Ext(gateApi, "Управление шлагбаумом", "Микросервис управления шлагбаумом")
System_Ext(domophoneApi, "Домофон", "Микросервис управления домофоном")

Rel(user, smartHouseSystem, "Управление устройствами")
Rel(smartHouseSystem, authService, "Авторизация и аутентификация пользователей")
Rel(smartHouseSystem, domophoneApi, "Управление домофоном")
Rel(smartHouseSystem, gateApi, "Управление шлагбаумом")
@enduml